---
- name: Configure custom browser flow
  community.general.keycloak_authentication_v2:
    auth_keycloak_url: "{{ keycloak_url }}"
    auth_realm: master
    auth_client_id: "{{ keycloak_ansible_client_id }}"
    auth_client_secret: "{{ vault_keycloak_ansible_client_secret }}"
    validate_certs: "{{ validate_certs | default(true) }}"

    realm: "{{ keycloak_realm_name }}"
    alias: browser-passkeys-only
    authenticationExecutions:
      - providerId: auth-cookie
        requirement: ALTERNATIVE
      - subFlow: browser-passkey-only-forms
        requirement: ALTERNATIVE
        authenticationExecutions:
          - providerId: auth-username-form
            requirement: REQUIRED
          - providerId: auth-password-form
            requirement: REQUIRED

- name: Bind browser flow to realm
  community.general.keycloak_realm:
    auth_keycloak_url: "{{ keycloak_url }}"
    auth_realm: master
    auth_client_id: "{{ keycloak_ansible_client_id }}"
    auth_client_secret: "{{ vault_keycloak_ansible_client_secret }}"
    validate_certs: "{{ validate_certs | default(true) }}"

    realm: "{{ keycloak_realm_name }}"
    browserFlow: browser-passkeys-only
