---
- name: Configure custom registration flow
  community.general.keycloak_authentication_v2:
    auth_keycloak_url: "{{ keycloak_url }}"
    auth_realm: master
    auth_client_id: "{{ keycloak_ansible_client_id }}"
    auth_client_secret: "{{ vault_keycloak_ansible_client_secret }}"
    validate_certs: "{{ validate_certs | default(true) }}"

    realm: "{{ keycloak_realm_name }}"
    alias: registration-passkeys-only
    authenticationExecutions:
      - subFlow: registration-passkey-only-forms
        subFlowType: form-flow
        requirement: REQUIRED
        authenticationExecutions:
          - providerId: registration-user-creation
            requirement: REQUIRED

- name: Bind registration flow to realm
  community.general.keycloak_realm:
    auth_keycloak_url: "{{ keycloak_url }}"
    auth_realm: master
    auth_client_id: "{{ keycloak_ansible_client_id }}"
    auth_client_secret: "{{ vault_keycloak_ansible_client_secret }}"
    validate_certs: "{{ validate_certs | default(true) }}"

    realm: "{{ keycloak_realm_name }}"
    registrationFlow: registration-passkeys-only
