services:
  db:
    labels:
      - dev.orbstack.domains=db.id.ffxiv.local
  iam:
    command: start --spi-theme--static-max-age=-1 --spi-theme--cache-themes=false --spi-theme--cache-templates=false
    environment:
      KC_HOSTNAME: https://id.ffxiv.local
    labels:
      - dev.orbstack.domains=id.ffxiv.local
      - dev.orbstack.http-port=8080

volumes:
  db:
    name: ffxiv-id-db
