services:
  db:
    labels:
      - dev.orbstack.domains=db.id.ffxiv.local
  iam:
    image: quay.io/keycloak/keycloak:26.4.5
    command: start --spi-theme--static-max-age=-1 --spi-theme--cache-themes=false --spi-theme--cache-templates=false
    environment:
      KC_HOSTNAME: https://id.ffxiv.local
      KC_TRUSTSTORE_PATHS: /etc/ssl/certs/orbstack-root.crt
    labels:
      - dev.orbstack.domains=id.ffxiv.local
      - dev.orbstack.http-port=8080
    volumes:
      - ./theme:/opt/keycloak/themes/ffxiv

volumes:
  db:
    name: ffxiv-id-db
