services:
  db:
    labels:
      - dev.orbstack.domains=db.id.ffxiv.local
  iam:
    image: ffxiv-id
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      KC_HOSTNAME: https://id.ffxiv.local
      KC_TRUSTSTORE_PATHS: /etc/ssl/certs/orbstack-root.crt
    labels:
      - dev.orbstack.domains=id.ffxiv.local
      - dev.orbstack.http-port=8080
    volumes:
      - ./theme:/opt/keycloak/themes/ffxiv

volumes:
  db:
    name: ffxiv-id-db
