---
- name: Configure Steam identity provider
  community.general.keycloak_identity_provider:
    auth_keycloak_url: "{{ keycloak_url }}"
    auth_realm: master
    auth_client_id: "{{ keycloak_ansible_client_id }}"
    auth_client_secret: "{{ vault_keycloak_ansible_client_secret }}"
    validate_certs: "{{ validate_certs | default(true) }}"

    realm: "{{ keycloak_realm_name }}"
    provider_id: steam
    enabled: true
    alias: steam
    display_name: Steam
    config:
      syncMode: "FORCE"
      apiKey: "{{ vault_steam_api_key | default('') }}"
