keycloak_url: https://ffxiv.id
passkey_relying_party_entity_name: FFXIV ID
passkey_relying_party_id: ffxiv.id

clients:
- client_id: monitoring
  name: Uptime Kuma
  description: Access to monitoring endpoints for Uptime Kuma.
  client_credentials_flow: true

- client_id: netstone-api
  name: Netstone API
  description: Pseudo client for Netstone API. Login is not actually possible, this is currently only used for audience mapping.

- client_id: alyx-discord
  name: Alyx Discord
  description: Alyx retrieves data from the Lodestone to create character sheets.
  client_credentials_flow: true
  jwks_url: https://alyx.eorzea.online/.well-known/jwks

- client_id: infinite-backlog
  name: Infinite Backlog
  description: Infinite Backlog retrieves data from the Lodestone for its FFXIV integration.
  client_credentials_flow: true
  certificate: "MIICqDCCAk2gAwIBAgIUIxfjU8ti1SCt7Kc02nEmlcXqj5cwCgYIKoZIzj0EAwIwgagxCzAJBgNVBAYTAk5MMRYwFAYDVQQIDA1Ob29yZCBCcmFiYW50MRIwEAYDVQQHDAlFaW5kaG92ZW4xGTAXBgNVBAoMEEluZmluaXRlIEJhY2tsb2cxCzAJBgNVBAsMAklCMRwwGgYDVQQDDBNpbmZpbml0ZWJhY2tsb2cubmV0MScwJQYJKoZIhvcNAQkBFhhpbmZvQGluZmluaXRlYmFja2xvZy5uZXQwHhcNMjYwMzAyMTczNTE0WhcNMjcwMzAyMTczNTE0WjCBqDELMAkGA1UEBhMCTkwxFjAUBgNVBAgMDU5vb3JkIEJyYWJhbnQxEjAQBgNVBAcMCUVpbmRob3ZlbjEZMBcGA1UECgwQSW5maW5pdGUgQmFja2xvZzELMAkGA1UECwwCSUIxHDAaBgNVBAMME2luZmluaXRlYmFja2xvZy5uZXQxJzAlBgkqhkiG9w0BCQEWGGluZm9AaW5maW5pdGViYWNrbG9nLm5ldDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABMVjUxa67Ynf9zZ91H4rxNVg5JaHi9brdTZo2JD6p2uUgej3ah4q5yw0Y+q+2Hj4vDIZ8adM3Cr2J7y/oevaUFKjUzBRMB0GA1UdDgQWBBT8oUTuxDrzliktEtxrZGejpSQO6DAfBgNVHSMEGDAWgBT8oUTuxDrzliktEtxrZGejpSQO6DAPBgNVHRMBAf8EBTADAQH/MAoGCCqGSM49BAMCA0kAMEYCIQCcgHh/cfwFaTQ+BFtQg04VywTLa8Skqz6zs1CYrTsNlQIhANY5oTIcGzMSaml63AzqZwwyUdfQSsaUehbH7KfLRW9f"
