keycloak_url: https://staging.ffxiv.id
passkey_relying_party_entity_name: FFXIV ID Staging
passkey_relying_party_id: staging.ffxiv.id

clients:
- client_id: monitoring
  name: Uptime Kuma
  description: Access to monitoring endpoints for Uptime Kuma.
  client_credentials_flow: true

- client_id: netstone-api
  name: Netstone API
  description: Pseudo client for Netstone API. Login is not actually possible, this is currently only used for audience mapping.

- client_id: alyx-discord
  name: Alyx Discord
  description: Alyx retrieves data from the Lodestone to create character sheets.
  client_credentials_flow: true
  jwks_url: https://alyx.staging.eorzea.online/.well-known/jwks

- client_id: infinite-backlog
  name: Infinite Backlog
  description: Infinite Backlog retrieves data from the Lodestone for its FFXIV integration.
  client_credentials_flow: true
  certificate: "MIICqDCCAk2gAwIBAgIUNXfnT/t8G/luOEP3IVg2gychWGowCgYIKoZIzj0EAwIwgagxCzAJBgNVBAYTAk5MMRYwFAYDVQQIDA1Ob29yZCBCcmFiYW50MRIwEAYDVQQHDAlFaW5kaG92ZW4xGTAXBgNVBAoMEEluZmluaXRlIEJhY2tsb2cxCzAJBgNVBAsMAklCMRwwGgYDVQQDDBNpbmZpbml0ZWJhY2tsb2cubmV0MScwJQYJKoZIhvcNAQkBFhhpbmZvQGluZmluaXRlYmFja2xvZy5uZXQwHhcNMjYwMzAyMTczNDE3WhcNMjcwMzAyMTczNDE3WjCBqDELMAkGA1UEBhMCTkwxFjAUBgNVBAgMDU5vb3JkIEJyYWJhbnQxEjAQBgNVBAcMCUVpbmRob3ZlbjEZMBcGA1UECgwQSW5maW5pdGUgQmFja2xvZzELMAkGA1UECwwCSUIxHDAaBgNVBAMME2luZmluaXRlYmFja2xvZy5uZXQxJzAlBgkqhkiG9w0BCQEWGGluZm9AaW5maW5pdGViYWNrbG9nLm5ldDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABNw7dVBzowFcqRKAiDohLejTftEvSV1KiNmrjNjqkE2Pzt4eeaKmGnoDpjueNjwpjFGhxnTJ+7HL8OkFyWnrDUqjUzBRMB0GA1UdDgQWBBTQydzHf0xg2i8hmKOqZKENuMZYTDAfBgNVHSMEGDAWgBTQydzHf0xg2i8hmKOqZKENuMZYTDAPBgNVHRMBAf8EBTADAQH/MAoGCCqGSM49BAMCA0kAMEYCIQDau271SWXzWk2nQGx0+u8UQKwPsa77SICwaIGITkQM/QIhAJI+9bxrw4wl2/Ssb4XoRVSYe3qmlbr6qjPvnr4B37DP"
